"""empty message

Revision ID: 3ea71fbbf708
Revises: bb8a5a813718
Create Date: 2020-06-09 21:27:21.289427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea71fbbf708'
down_revision = 'bb8a5a813718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name_esp', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'name_esp')
    # ### end Alembic commands ###
